### ISSUE TITLE
Accuracy and Precision

### ISSUE THREAD

**Issue by DarioS** [Sydney-Informatics-Hub/Germline-ShortV#10]
Any hope of getting a university-wide DRAGEN licence?

> The best-performing short-read submissions used statistical variant-calling algorithms with a graph reference rather than a standard linear reference (e.g., DRAGEN and Seven Bridges methods)

Source: [PrecisionFDA Truth Challenge V2: Calling Variants from Short and Long Reads in Difficult-to-map Regions](https://www.cell.com/cell-genomics/fulltext/S2666-979X(22)00058-1), _Cell Genomics_.

**Comment by georgiesamaha** [comment]
Confirmed no plans to purchase a DRAGEN license in the near future via email.
