### ISSUE TITLE
gatk/4.1.2.0 Deleted from Gadi

### ISSUE THREAD

**Issue by DarioS** [Sydney-Informatics-Hub/Germline-ShortV#11]
To keep consistency with my previous analysis I want to use version 4.1.2.0. But, it has been removed from Gadi by administrators. So, I edited my command to use a local file but I can't avoid errors.

```
java -jar "-Xms32g -Xmx32g -Djava.io.tmpdir=${PBS_JOBFS}" /home/562/ds6924/apps/gatk/4.1.2.0/gatk-package-4.1.2.0-local.jar \
        GenomicsDBImport \
        ...        ...
```

and in PBS file `module load java/jdk-8.40`. I previously also tried `-Xms44g -Xmx48g` and `-Xmx58g` but there is always an error such as:

```
Thu Aug  3 12:28:00 AEST 2023 : Start GATK 4 GenomicsDBImport. Reference: ../Reference/hs38DH.fasta; Cohort: allNormals; Interval: ../Reference/ShortV_intervals/0001-scattered.interval_list; Sample map: ./Inputs/allNormals.sample_map; Out: ../allNormals_GenomicsDBImport/0001; Logs: ./Logs/GATK4_GenomicsDBImport; Threads: 1
Invalid initial heap size: -Xms32g -Xmx32g -Djava.io.tmpdir=/jobfs/91802870.gadi-pbs
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

How can users successfully avoid the deleted module issue? 4.1.8.1 could also soon be deleted without warning by N.C.I. staff.

**Comment by calizilla** [comment]
Hi Dario, I will re-install GATK v 4.1.2.0 in your project's gdata so you don't need to change versions. I have emailed you some instructions on using module commands with locally installed software.
