### ISSUE TITLE
Old nci-parallel Referenced by HaplotypeCaller Stage

### ISSUE THREAD

**Issue by DarioS** [Sydney-Informatics-Hub/Germline-ShortV#2]
It should be 1.0.0a to avoid the defective version being used.

https://github.com/Sydney-Informatics-Hub/Germline-ShortV/blob/022697fa6900cb7accebe22698e43387c96386ad/gatk4_hc_run_parallel.pbs#L48

Also, is `module load openmpi/4.1.0` necessary alongside this? I can't remember exactly what Ben Menadue said.

**Comment by tracychew** [comment]
Fixed
