### ISSUE TITLE
No Recent Resource Guide Table

### ISSUE THREAD

**Issue by DarioS** [Sydney-Informatics-Hub/Germline-ShortV#3]
In section Benchmarking Metrics, there is a table for stage 1 displayed, but not for subsequent stages. It would be nice to have updated timings based on the latest versions of OpenMPI and nci-parallel and use of jobFS to guide the choices.

**Comment by tracychew** [comment]
Documentation now updated with benchmarking metrics for each step, 6 platinum genome samples.
