### ISSUE TITLE
GenomicsDBimport Rerun Script Missing GATK4 Module

### ISSUE THREAD

**Issue by DarioS** [Sydney-Informatics-Hub/Germline-ShortV#5]
`module load gatk` missing from `gatk4_genomicsdbimport_missing_run_parallel.pbs` but in `gatk4_genomicsdbimport_run_parallel.pbs`.
Interval logs show error `./gatk4_genomicsdbimport_missing.sh: line 52: gatk: command not found`.

**Comment by georgiesamaha** [comment]
Fixed! https://github.com/Sydney-Informatics-Hub/Germline-ShortV/blob/820f26ae56ca4adba61428db4e23d5e8918a081c/gatk4_genomicsdbimport_missing_run_parallel.pbs#L51
