### ISSUE TITLE
Genotype GVCFs Scripts Checks Incorrect Folder

### ISSUE THREAD

**Issue by DarioS** [Sydney-Informatics-Hub/Germline-ShortV#6]
During the very first run, the output folder is `../${configName}_GenotypeGVCFs/` But the check script looks for a folder with `_1` at the end of it and prints 3200 lines of missing files to the command line and mistakenly reports that:

```
Fri Dec  3 09:38:47 AEDT 2021: There are 3200 intervals that need to be re-run.
Fri Dec  3 09:38:47 AEDT 2021: Writing inputs to ./Inputs/gatk4_genotypegvcfs_missing_1.inputs
```

Novice users would not read the source code and wouldn't realise that `run_num=1` should be commented out, so I think the default should be it being commented out, so it works by default on the first run.

**Comment by georgiesamaha** [comment]
fixed https://github.com/Sydney-Informatics-Hub/Germline-ShortV/blob/0b97b5a76f15885d2b9786fdc13cf0696a813c46/gatk4_genotypegvcfs_check.sh#L37
