### ISSUE TITLE
gatk4_gather_sort_vcfs.pbs Samples Hard-coded to Platinum Genomes

### ISSUE THREAD

**Issue by DarioS** [Sydney-Informatics-Hub/Germline-ShortV#7]
Perhaps it could accept a configuration file via user input.

**Comment by DarioS** [comment]
Also for gatk4_vqsr.pbs.

**Comment by georgiesamaha** [comment]
fixed hard coding @ https://github.com/Sydney-Informatics-Hub/Germline-ShortV/commit/28b2bd2307a85fda9621852904db660ba0c0516c

Will consider a configuration script like fastq-to-BAM in the future.
